config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :show, :edit, :update]
  resources :jobs
  resources :homes
  resources :dogs

  get "signup", to: "users#new", as: 'signup'
  get "users/:id/dogs", to: "users#dogs", as: 'user_dogs'
  patch "users/:id/dogs", to: "users#assign_dogs"
  get "/signin", to: "sessions#new", as: 'signin'
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy", as: "signout"
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many :user_dogs
  has_many :users, through: :user_dogs

  
end

app/models/home.rb
class Home < ApplicationRecord
  belongs_to :user
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_one :job
  has_one :home
  has_many :user_dogs
  has_many :dogs, through: :user_dogs
  has_secure_password

  validates :username, uniqueness: true
  validates :password, length: { minimum: 6 }, on: :create

  def job
    Job.find_by(id: self.job_id)
  end

  def home
    Home.find_by(id: self.home_id)
  end

  def assign_job_points
    points = 0
    x = Job.find(self.job_id).salary
    if x <= 25000
      points += 1
    elsif x > 25000 && x <= 70000
      points += 2
    else
      points += 3
    end
    y = Job.find(self.job_id).num_hours_at_work
    if y < 7
      points += 3
    else
      points -= 3
    end
    if points < 0
      points = 0
    end
    points

  end

  def assign_home_points #to be edited
    points = assign_job_points
    x = Home.find(self.home_id)
    if x.apt_or_house.downcase == "apartment"
      points += 2
    else
      points += 4
    end
    y = Home.find(self.home_id)
    if y.city_or_suburb.downcase == "suburb"
      points += 4
    else
      points += 2
    end
    z = Home.find(self.home_id)
    if z.num_of_rooms < 2
      points += 1
    else
      points += 2
    end
    a = Home.find(self.home_id)
    if a.num_of_occupants < 2
      points += 1
    else
      points += 2
    end
    b = Home.find(self.home_id)
    if b.kids == nil
      points += 1
    else
      points += 2
    end
    c = Home.find(self.home_id)
    if c.pets == nil
      points += 1
    else
      points += 2
    end
    points
  end

  def get_list_of_dogs
    if (self.assign_home_points >= 1) && (self.assign_home_points <= 8)
      Dog.where("size = ? and (barking_level = ? or barking_level = ?)  and (energy_level = ? or energy_level = ?)", 's', 1, 2, 'Not very active','Somewhat active')

    elsif (self.assign_home_points >= 9) && (self.assign_home_points <= 14)
      Dog.where("(size = ? or size = ?) and (barking_level = ? or barking_level = ?)  and (energy_level = ? or energy_level = ?)", 's', 'm', 1, 2, 'Very active','Somewhat active')

    elsif (self.assign_home_points >= 15) && (self.assign_home_points <= 22)
      Dog.where("(energy_level = ? or energy_level = ?) and children_friendly =? ", 'Very active','Somewhat active', true)
    end
  end




end

app/models/user_dog.rb
class UserDog < ApplicationRecord
  belongs_to :user
  belongs_to :dog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authorized

  helper_method :logged_in?

  # who is my current user
  # am i logged in or not
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end


  def logged_in?
    !!current_user
  end


  def authorized
    if logged_in?
    else
      redirect_to signin_path
    end
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :authorized, only: [:index]


  def show
    @dog = Dog.find(params[:id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:create, :new]

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])

      session[:user_id] = user.id
      flash[:message] = "Welcome #{user.username}!"
      redirect_to user_path(user)
    else
      flash[:message] = "Wrong username and password"
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/user_dogs_controller.rb
class UserDogsController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:index, :new, :create]

  def index
    @user = User.new
  end

  def new

    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to edit_user_path(@user)
    else
      flash[:success] = "Password must be a minimum of 6 characters"
      render 'new'
    end

  end


  def show
    @user = User.find(params[:id])
  end

  def dogs
    @user = User.find(params[:id])

    if !(@user.job_id.nil?)
      #later will be sessions
     @filtered = @user.get_list_of_dogs
    end
  end

  def assign_dogs

    @user = User.find(params[:id])

    params[:user][:dogs].select{|x| !x.empty?}.each do |dog_id|
      if !@user.dogs.include?(Dog.find(dog_id.to_i))
        @user.dogs << Dog.find(dog_id.to_i)
      end
    end
    redirect_to user_path(@user)
  end

  def edit

    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

      if @user.job_id.nil?
        @job = Job.create(salary: params[:user][:job][:salary], num_hours_at_work: params[:user][:job][:num_hours_at_work])
        @user.job_id = @job.id
        @user.save
      else

        @job = Job.find(@user.job_id)
        @job.update(salary: params[:user][:job][:salary], num_hours_at_work: params[:user][:job][:num_hours_at_work])
      end
      if  @user.home_id.nil? #WHY ADD USERID

        @home = Home.create(city_or_suburb: params[:user][:home][:city_or_suburb], apt_or_house: params[:user][:home][:apt_or_house], num_of_rooms: params[:user][:home][:num_of_rooms], num_of_occupants: params[:user][:home][:num_of_occupants], kids: params[:user][:home][:kids], pets: params[:user][:home][:pets], user_id: @user.id)
        @user.home_id = @home.id
        @user.save
      else
        @home = Home.find(@user.home_id)
        @home.update(city_or_suburb: params[:user][:home][:city_or_suburb], apt_or_house: params[:user][:home][:apt_or_house], num_of_rooms: params[:user][:home][:num_of_rooms], num_of_occupants: params[:user][:home][:num_of_occupants], kids: params[:user][:home][:kids], pets: params[:user][:home][:pets], user_id: @user.id)
      end
      redirect_to user_dogs_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :job_id, :home_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/show.html.erb
<div class="center_div">
  <h1 class="text-center"><%=@dog.breed%></h1>
  <img src="<%=@dog.link%>" alt="<%=@dog.breed%>" style="max-width: 100%; height: auto;">
  <br>
  <ul class="text-center">
    <label>Personality:</label>
    <li><%=@dog.personality%></li>
    <label>Energy Level:</label>
    <li><%=@dog.energy_level%></li>
    <label>Size:</label>
    <li><%=@dog.size%></li>
    <label>Barking Level (1: Quiet - 3: Intermittent Barking):</label>
    <li><%=@dog.barking_level%></li>
    <a href="https://www.petfinder.com/search/dogs-for-adoption/us/ny/new-york-city/?distance=100&sort%5B0%5D=recently_added">ADOPT A DOG TODAY CLICK HERE</a>

  </ul>
</div>


<img src="https://goo.gl/D4iUjt" id="bg" alt="dog_home">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Furever Furend</title>

    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'custom.css' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-custom navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"></a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to "Sign Out", signout_path, method: :delete %></li>
            <li><%= link_to "My Profile", user_path(@current_user) %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>

          <% flash.each do |key, value| %>
            <em><%= value %></em>
          <% end %>

        </ul>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/users/dogs.html.erb
<div class="row">

  <div class="col-sm-6">
    <% if @filtered %>
    <h1>List of potential Furends:</h1>
    <h3>There are <%=@filtered.count%> furends we recommend for you!</h3>

      <%@filtered.each do |dog|%>
        <div class="col-sm-5">
            <img src="<%=dog.link%>" alt="<%=dog.breed%>" style="max-width: 80%; height: auto;">
            <p class="card-text"><%=link_to dog.breed, dog_path(dog)%></p>

        </div>
      <% end %>
    <%end%>
  </div>


  <!-- user/:id/:edit -->
  <div class="col-sm-6 pad_left">
  <div class="col-sm-2">
    <h3>Add Dogs</h3>
    <div class="form">
      <%= form_tag("/users/#{@user.id}/dogs", method: :patch, class: 'checkbox') do %>

        <%=collection_check_boxes :user, :dogs, @filtered, :id, :breed %> <br>

        <%= submit_tag "Add Dogs", class: 'btn btn-success' %>
      <%end%><br>
    </div>
  </div>
  <!-- </div> -->

</div>

<img src="https://goo.gl/AQYuCN" id="bg" alt="dog_home">

app/views/users/edit.html.erb
<div class="move_left">
  <h1>Enter Personal Info for <%=@user.username %> </h1>
  <div class="center_div_info">
    <%= form_tag("/users/#{@user.id}", method: :put) do %>
    <h2>Job Info</h2>
    <%= label_tag 'salary' %> <br>
    <p> <%= number_field_tag 'user[job][salary]', @user.job ? @user.job.salary : "", class: 'form-control' %> </p>
    <%= label_tag 'Work Hours' %> <br>
    <p> <%= number_field_tag 'user[job][num_hours_at_work]', @user.job ? @user.job.num_hours_at_work : "", class: 'form-control' %> </p>
    <h2>Home Info</h2>
    <%= label_tag 'Location (city | suburb)' %> <br>
    <p> <%= text_field_tag 'user[home][city_or_suburb]', @user.home ? @user.home.city_or_suburb : "", class: 'form-control' %> </p>
    <%= label_tag 'Type (apartment | house)' %> <br>
    <p> <%= text_field_tag 'user[home][apt_or_house]', @user.home ? @user.home.apt_or_house : "", class: 'form-control' %> </p>
    <%= label_tag 'Number of Rooms' %> <br>
    <p> <%= number_field_tag 'user[home][num_of_rooms]', @user.home ? @user.home.num_of_rooms : "", class: 'form-control' %></p>
    <%= label_tag 'Number of Occupants' %> <br>
    <p> <%= number_field_tag 'user[home][num_of_occupants]', @user.home ? @user.home.num_of_occupants : "", class: 'form-control' %></p>
    <%= label_tag 'Any Children? (check if yes):' %>
    <%= check_box_tag 'user[home][kids]', true %></p>
    <%= label_tag 'Any Pets? (check if yes):' %>
    <%= check_box_tag 'user[home][pets]', true %> </p>
    <%= submit_tag "Find Your Fur-end!", class: 'btn btn-success' %>
    <% end %>

  </div>
</div>


<img src="https://goo.gl/AQYuCN" id="bg" alt="dog_home">

app/views/users/index.html.erb
<div class="center_div_index">

<h1 style="font-family:verdana;" class = 'text-center'>Sign Up <br> & Find Your Furever Furend!</h1>
<br>
<div class="center_div">
  <%= form_for @user, url: users_path, method: :post  do |f|%>
    <%=f.label :username  %><br>
    <%=f.text_field(:username, {:class => 'form-control', placeholder: "Username"})%><br>
    <%=f.label :password  %><br>
    <%=f.password_field(:password, {:class => 'form-control',placeholder: "Password (minimum 6 characters)"})%><br>
    <%=f.label :confirm_password  %><br>
    <%=f.password_field(:password_confirmation, {:class => 'form-control', placeholder: "Password (minimum 6 characters)"})%><br>
    <%=f.submit({:class => 'btn btn-success'})%>
  <% end %>
</div>

</div>



<img src="https://goo.gl/Fvy8ve" id="bg" alt="dog_home">

app/views/users/new.html.erb
<!-- Create username/pw_digest -->
<div style="background-color: rgba(211, 211, 211, 0.5); width:50%; margin-left: auto; margin-right: auto; margin-top: auto; height: 350px">
  <h1 class = 'text-center'>Sign Up</h1>
  <div class="center_div">
    <%= form_for @user, url: users_path, method: :post  do |f|%>
      <%=f.label :username  %><br>
      <%=f.text_field(:username, {:class => 'form-control', placeholder: "Username"})%><br>
      <%=f.label :password  %><br>
      <%=f.password_field(:password, {:class => 'form-control', placeholder: "Password (minimum 6 characters)"})%><br>
      <%=f.label :confirm_password  %><br>
      <%=f.password_field(:password_confirmation, {:class => 'form-control', placeholder: "Password (minimum 6 characters)" })%><br>
      <%=f.submit({:class => 'btn btn-success'})%>
    <% end %>
  </div>
</div>
<img src="https://goo.gl/Fvy8ve" id="bg" alt="dog_home">

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-4">
    <%if @user.dogs.count == 0%>
      <p>You have no saved dogs yet!</p>
    <%else%>
    <h1>Your list of saved dogs:</h1>
    <h3>You have <%=@user.dogs.count%> saved dogs</h3>
      <%@user.dogs.each do |dog|%>
      <div class = 'col-sm-6'>
        <img src='<%=dog.link%>' alt="<%=dog.breed%>" style="max-width: 80%; height: auto;">
        <figcaption><%=link_to dog.breed, dog_path(dog)%></figcaption>

      </div>

      <% end %>

    <%end%>
  </div>
  <div class="col-sm-5"></div>
  <div class="col-sm-3">
    <div class="move_left">
      <h2 class='text-center'>Your Current Profile</h2>
      <ul>
        <%= label_tag 'Salary' %> <br>
        <li><%=@user.job.salary%></li>
        <%= label_tag 'Work Hours' %> <br>
        <li><%=@user.job.num_hours_at_work%></li>
        <%= label_tag 'Home Location:' %> <br>
        <li><%=@user.home.city_or_suburb%></li>
        <%= label_tag 'Home Type' %> <br>
        <li><%=@user.home.apt_or_house%></li>
        <%= label_tag 'Number of Rooms' %> <br>
        <li><%=@user.home.num_of_rooms%></li>
        <%= label_tag 'Number of Occupants' %> <br>
        <li><%=@user.home.num_of_occupants%></li>
      </ul>
    <div class="move_btn_right">
      <form action="/users/<%=@user.id%>/edit" method='get'>
        <button type='submit' class='btn btn-success'>Update Personal Info</button>
      </form>
    </div>

    </div>





  </div>
</div>







<img src="https://goo.gl/AQYuCN" id="bg" alt="dog_home">

<!--  -->